### ISSUE TITLE
ModuleNotFoundError: No module named 'genweb'

### ISSUE THREAD

**Issue by pagerk** [marcpage/genweb#2]
I executed the following:
$ python3 -m genweb.build_web_pages /home/pagerk/sambashare/Famhist-todo/myfamily20190219.rmgc /home/pagerk/FamilyHistoryWeb/Individual_Web_Pages pagerk@gmail.com

and received the following error message:
/usr/bin/python3: Error while finding module specification for 'genweb.build_web_pages' (ModuleNotFoundError: No module named 'genweb')

It appears to be coming from the line:
from genweb import rmagic

**Comment by marcpage** [comment]
Can you do an la or a dir in that directory. Also, what is the output from python3 --version?

**Comment by marcpage** [comment]
`% python3 --version`
Python 3.9.6

`% pwd`
/Users/marcp/Documents/Development/genweb

`% ls -Flgs`
total 40
 8 -rw-r--r--   1 staff   2156 Feb  7 15:01 README.md
 0 drwxr-xr-x  13 staff    416 Feb  8 00:36 genweb/
24 -rwxr-xr-x@  1 staff  10236 Feb  9 12:56 pr_build.py*
 8 -rw-r--r--@  1 staff     95 Feb  7 10:15 requirements.txt
 0 drwxr-xr-x   7 staff    224 Feb  8 02:58 tests/

`% python3 -m genweb.build_web_pages ~/Desktop/dad_genweb/myfamily20221209.rmgc ~/Dropbox/FamilyHistory/html/Individual_Web_Pages pagerk@gmail.com`

That seems to work (I didn't wait for it to complete, but it was going for a few seconds).

**Comment by marcpage** [comment]
Make sure you are running `python3 -m genweb.build_web_pages` from the same directory that the `README.md` is in.
